name: all-demo-tests

on:
  workflow_dispatch:

concurrency:
  group: ci-demo

jobs:
  all-demo-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum -- npm run test:headed
        env:
          ENVIRONMENT_URL: https://dapp-citizen-react.vercel.app
          METAMASK_SETUP_NETWORK: ${{ vars.METAMASK_SETUP_NETWORK}}
          METAMASK_SETUP_PRIVATE_KEY: ${{secrets.METAMASK_SETUP_PRIVATE_KEY}}
          METAMASK_SETUP_PASSWORD: ${{secrets.METAMASK_SETUP_PASSWORD}}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: test-report/
          retention-days: 30